apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: demoagent
spec:
  byo:
    deployment:
      env:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            key: OPENAI_API_KEY
            name: demoagent-env
      - name: DOCKER_REPO
        valueFrom:
          secretKeyRef:
            key: DOCKER_REPO
            name: demoagent-env
      image: pmuir/demoagent:36
      replicas: 1
  type: BYO