apiVersion: agentgateway.dev/v1alpha1
kind: AgentgatewayPolicy
metadata:
  name: tool-policy
spec:
  targetRefs:
    - group: agentgateway.dev
      kind: AgentgatewayBackend
      name: mcp-backend
  backend:
    mcp: 
      authorization:
        action: Allow
        policy:  
          matchExpressions:
            - 'jwt.sub == "acf04f2b-f529-45ef-a2d8-5311fc3c8301" && mcp.tool.name == "printEnv"'
---
# apiVersion: agentgateway.dev/v1alpha1
# kind: AgentgatewayPolicy
# metadata:
#   name: jwt-policy
# spec:
#   targetRefs:
#     - group: gateway.networking.k8s.io
#       kind: Gateway
#       name: agentgateway
#   traffic:
#     jwtAuthentication:
#       # mode: Strict
#       mode: Permissive
#       providers:
#       - jwks:
#           inline: '{"keys":[{"alg":"RS256","e":"AQAB","kid":"wf_Ncb2F7FiqSEBWp2eeIIghXwLOCEG1YtAjhcWB5ds","kty":"RSA","n":"tx71LVqUIz67_Wv6s-9KlzxA-uOfHXzj9HScpGgB0nSxAWo2oWHwxa-vL85OI0iSl2caEHTwYXqZNbBInJD0rk72zroxN-rQVLucpVvdZgQSBgEtxg846EVSjD5DAlvXJ85QuaCRTW7cl3sFXriYzDQkytZhODWcuxxiqrFOgbUIn1RsII38JEKhkItENQQRO52DCmx0ISYVYqGIJY1wNgDciAZghnc0iqcweBPPiF9oKrtH_tRTDYLfJkJfD3KYG9ygV0VSJTaWs0VYmHe465IiDktCS9gxmf_GOkvLQCovhjrXiZsGesmIMSmWrqISdjNKFCP9387TS2yEcohjew"}]}'
---
apiVersion: kagent.dev/v1alpha2
kind: Agent
metadata:
  name: demoagent
spec:
  byo:
    deployment:
      env:
      - name: OPENAI_API_KEY
        valueFrom:
          secretKeyRef:
            key: OPENAI_API_KEY
            name: demoagent-env
      image: pmuir/demoagent:36
      replicas: 1
  type: BYO
  