apiVersion: gateway.kgateway.dev/v1alpha1
kind: Backend
metadata:
  name: mcp-backend
spec:
  type: MCP
  mcp:
    targets:
    - name: mcp-target
      static:
        host: server-everything.kagent.svc.cluster.local
        port: 3000
        protocol: StreamableHTTP